### ISSUE TITLE
Add User-Agent header

### ISSUE THREAD

**Issue by mendizalea** [huysentruitw/oauth2-client-handler#4]
Hi,

How I can add User-Agent header?

Thanks

**Comment by huysentruitw** [comment]
You should be able to do that on the `HttpClient` instance itself. Something like:

    httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko/20100101 Firefox/60.0");
